language: python
python:
  - 2.7
dist: trusty
branches:
 only:
 - master
 - staging
 - production
sudo: required
chmod: +x
services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u=makavelli2 -p=makavelli
      - docker build -t flask-app .
      - docker images
      - docker tag flask-app makavelli2/labs
      - docker push makavelli2/labs

deploy:
- provider: codedeploy
<<<<<<< HEAD
  revision_type: github
=======
  wait-until-deployed: true
>>>>>>> 5e513e06c680df63c5a91547a3872426994da7c5
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  application: flask-app
  deployment_group: flask-app
<<<<<<< HEAD
  region: us-west-1
=======
  region: us-west-1a
>>>>>>> 5e513e06c680df63c5a91547a3872426994da7c5
