language: python
python:
  - 2.7
dist: trusty
branches:
 only:
 - master
 - staging
 - production
sudo: required
chmod: +x
services:
  - docker
before_install:
  - docker build -t flask-app .
  - docker run -d -p 5000:5000 flask-app
