language: python
python:
  - 2.7
dist: trusty
sudo: required
chmod: +x
branches:
  only:
    - master
    - production
    - staging
services:
  - docker

before_script:
  - docker pull makavelli2/labs || true

script:
  - docker build -t flask-app .
  - docker run -d -p 80:5000 flask-app
  - docker tag flask-app makavelli2/labs

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  - provider: script
    script: docker push makavelli2/labs
    on:
      branch: master

  - provider: codedeploy
    revision_type: github
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    application: flask-app
    deployment_group: flask-app
    region: us-west-1