language: python
python:
  - 2.7
dist: trusty
branches:
 only:
 - master
 - staging
 - production
sudo: required
chmod: +x
services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u=makavelli2 -p=makavelli
      - docker build -t flask-app .
      - docker images
      - docker tag flask-app makavelli2/labs
      - docker push makavelli2/labs

