version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/flask-app
hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 20
      runas: ubuntu
  AfterInstall:
    - location: scripts/load_image.sh
      timeout: 10
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 10
      runas: ubuntu